### PR TITLE
Update introduction.md

### PR DESCRIPTION
**Pull request by ThomasWeiss**
- Added Cassandra API
- Adjusted some wording

### CODE REVIEW

**Comment by v-radelg** [comment]
Hi @ThomasWeiss , we are still in discussing, will update the decision later soon. 
		
Thanks for your support,

Microsoft C&E Localization Team

**Comment by gosali** [comment]
Hi @ThomasWeiss , we are still in discussing, will update the decision later soon. 
  
Thanks for your support,
Microsoft C&E Localization Team

**Comment by gosali** [comment]
Hi @ThomasWeiss, 

Could you please Sign the CLA Certificate so as to  implement your contribution in the Live website?

Thanks for your support,
Microsoft C&E Localization Team

**Comment by gosali** [comment]
@ThomasWeiss , Thank you for your feedback and suggestion! 
  
The suggestion will be merged to the production, we will re-release this articles in the next loc release round. 
  
Microsoft C&E Localization Team

**Pull request merged**
